"""
fishing_decision_agent.py

Unified Fishing Decision Agent for Blue Orbit (ORCA) — Step 20.

Coordinates the Unified Fishing Decision Engine and provides plain-language
narrative and practical advice for fishermen while guaranteeing that the
deterministic recommendation, scores, and risk classifications cannot be
altered or hallucinated by the LLM.
"""

import json
import logging
from typing import Optional, Any, Dict

import groq

from ..config import GROQ_API_KEY, LLM_MODEL, LLM_PROVIDER
from ..tools.fishing_decision_tool import FishingDecisionTool
from .schemas import FishingDecision, FishingDecisionAgentResponse
from ..services.temporal_resolver import TemporalResolution

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the Marine Decision Support Assistant for Blue Orbit (ORCA), an AI platform for fishermen and coastal monitors along the Indian West Coast.

You will receive a deterministic fishing recommendation generated by the Unified Fishing Decision Engine. The decision, scores, and limiting factors are 100% authoritative and mathematically verified.

YOUR MANDATE:
1. NEVER alter, override, or disagree with the engine's recommendation (FAVORABLE, CAUTION, NOT_RECOMMENDED, or INSUFFICIENT_DATA).
2. NEVER claim guaranteed fish catch, fish abundance, or absolute vessel safety.
3. Clearly summarize the conditions (Habitat, Weather, EEZ status).
4. Provide structured JSON with 'narrative' and 'advice' keys.

JSON Format:
{
  "narrative": "A concise, conversational summary of the conditions and recommendation.",
  "advice": "Practical maritime advice for the fisherman (e.g. check local advisories, inspect gear, monitor wave chop)."
}
"""


class FishingDecisionAgent:
    """
    Synthesizes habitat suitability, weather safety, and EEZ boundary status
    into a unified fishing decision with plain-language narration.
    """

    def __init__(
        self,
        llm_client: Optional[Any] = None,
        tool: Optional[FishingDecisionTool] = None,
    ):
        if LLM_PROVIDER != "groq":
            raise ValueError(f"LLM_PROVIDER '{LLM_PROVIDER}' is not supported. Currently only 'groq' is implemented.")

        if llm_client is not None:
            self._llm = llm_client
        else:
            if not GROQ_API_KEY:
                raise EnvironmentError("GROQ_API_KEY is not set. Please add it to backend/.env.")
            self._llm = groq.Groq(api_key=GROQ_API_KEY)

        self._model = LLM_MODEL
        self._tool = tool or FishingDecisionTool()

    def run(
        self,
        latitude: float,
        longitude: float,
        date_str: str,
        query_text: str = "",
        temporal_resolution: Optional[TemporalResolution] = None,
    ) -> FishingDecisionAgentResponse:
        """
        Execute unified fishing decision assessment.
        """
        # 1. Execute deterministic orchestration tool
        tool_result = self._tool.get_fishing_decision(
            latitude=latitude,
            longitude=longitude,
            date_str=date_str,
            temporal_resolution=temporal_resolution,
            query_text=query_text,
        )

        decision: FishingDecision = tool_result.get("decision")
        if not decision:
            return FishingDecisionAgentResponse(
                success=False,
                decision=None,
                error="Failed to evaluate fishing decision.",
            )

        # Fallback default narrative
        fallback_narrative = (
            f"Fishing conditions are evaluated as {decision.decision} "
            f"(Overall Score: {decision.overall_score if decision.overall_score is not None else 'N/A'}/100). "
            + " ".join(decision.reasons)
        )
        fallback_advice = " ".join(decision.warnings) if decision.warnings else "Always verify local sea conditions with coastal port authorities before setting sail."

        # If data is insufficient or future date, use fast deterministic narrative
        if decision.decision == "INSUFFICIENT_DATA":
            return FishingDecisionAgentResponse(
                success=True,
                decision=decision,
                narrative=fallback_narrative,
                advice=fallback_advice,
            )

        # 2. Query LLM strictly for natural phrasing
        summary_payload = {
            "decision": decision.decision,
            "overall_score": decision.overall_score,
            "confidence": decision.confidence,
            "limiting_factor": decision.limiting_factor,
            "habitat_score": decision.habitat_score,
            "habitat_status": decision.habitat_status,
            "weather_score": decision.weather_score,
            "weather_risk": decision.weather_risk,
            "geofence_status": decision.geofence_status,
            "reasons": decision.reasons,
            "warnings": decision.warnings,
        }

        user_prompt = (
            f"A fisherman asked: \"{query_text or 'Can I go fishing today?'}\"\n\n"
            f"Here is the deterministic engine recommendation:\n"
            f"{json.dumps(summary_payload, indent=2)}\n\n"
            "Generate JSON with 'narrative' and 'advice'."
        )

        narrative = fallback_narrative
        advice = fallback_advice

        try:
            completion = self._llm.chat.completions.create(
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                model=self._model,
                temperature=0.2,
                max_tokens=400,
                response_format={"type": "json_object"},
            )
            raw = completion.choices[0].message.content
            parsed = json.loads(raw)
            narrative = parsed.get("narrative", fallback_narrative)
            advice = parsed.get("advice", fallback_advice)
        except Exception as e:
            logger.warning(f"FishingDecisionAgent LLM call failed: {e}. Using deterministic fallback.")

        return FishingDecisionAgentResponse(
            success=True,
            decision=decision,
            narrative=narrative,
            advice=advice,
        )
